version: '3'

services:
  builder:
    build: 
      context:  builder
    image: builder
    container_name: builder
    volumes:
      - /d01/builder:/builder/

  tomcat:
    build: 
      context:  tomcat
    image: tomcat
    ports:
      - 8011:8080
    container_name: tomcat
    volumes:
      - /d01/builder:/usr/local/tomcat/webapps/ 
    
