version: '3'

services:
  builder:
    build: 
      context: builder/
    volumes:
      - papka:/builder

   
  tomcat:
    build: 
      context: tomcat/ 
    ports:
      - 8011:8080
    volumes:
      - papka:/usr/local/tomcat/webapps
    depends_on:   
      - builder

volumes:
  papka:
